spring:
  application:
    name: Seravia
  threads:
    virtual:
      enabled: true #For fast IO :)
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4 #todo use 4o instead of this and o4-mini se chain banani
  data:
    mongodb:
      uri: ${MONGO_ATLAS_URL_SERAVIA}
      auto-index-creation: true
      database: seravia_db

  cassandra:
    # Connection settings
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1

    # Authentication (matches Docker Compose)
    username: cassandra
    password: cassandra

    # Keyspace configuration
    keyspace: spring_keyspace
    schema-action: CREATE_IF_NOT_EXISTS

    # Connection tuning
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    request:
      timeout: 10s
      throttle-timeout: 1s

email:
  sendgrid:
    config:
      apiKey: ${SENDGRID_API_KEY}
      fromEmail: "ahnisaneja@gmail.com"

app:
  base-url: "http://localhost:5173"
  password-reset-url: "/reset-password"
security:
  allowedOrigins:
    - "http://localhost:5173"

management:
  endpoint:
    health:
      show-details: "always"  # Always show detailed health info (safe for internal use)
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/monitor"  # Moves all Actuator endpoints under "/monitor"
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000
admin:
  bootstrap:
    enabled: ${ADMIN_BOOTSTRAP_ENABLED:false}   # Default off for safety (dev only)
    resource: ${ADMIN_BOOTSTRAP_RESOURCE:classpath:/bootstrap/users.json}  # Default to classpath, can point to file:// or even http:// if needed (super flexible)
  user:
    enabled: ${ADMIN_ENABLED:true}  # Default false for safety
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@example.com}
    password: ${ADMIN_PASSWORD:admin123}  # Set via env var in production
    preferences:
      reportFrequency: BIWEEKLY  # Enum value
      language: ENGLISH          # Enum value
      themePreference: DARK      # Enum value
      supportStyle: MINDFUL   # Enum value
      age: 22                    # Integer value
      gender: MALE               # Enum value
server:
  port: 8081

milvus:
  cloud:
    uri: ${MILVUS_CLOUD_URI}
    token: ${MILVUS_CLOUD_TOKEN}
    username: ${MILVUS_CLOUD_USERNAME}
    password: ${MILVUS_CLOUD_PASSWORD}

vector:
  batching:
    enabled: false
  store:
    database-name: ${VECTOR_STORE_DATABASE_NAME:default}
    collection-name: ${VECTOR_STORE_COLLECTION_NAME:vector_store1}
    metric-type: ${VECTOR_STORE_METRIC_TYPE:COSINE}
    index-type: ${VECTOR_STORE_INDEX_TYPE:IVF_FLAT}
    embedding-dimension: ${VECTOR_STORE_EMBEDDING_DIMENSION:1536}
    initialize-schema: ${VECTOR_STORE_INITIALIZE_SCHEMA:true}
scheduler:
  remind-users:
    cron: "0 56 19 * * ?"   # 7:52 PM IST
    zone: "Asia/Kolkata"
  check-reports:
    cron: "0 56 19 * * ?"   # 7:20 PM IST
    zone: "Asia/Kolkata"
