spring:
  application:
    name: Seravia
  threads:
    virtual:
      enabled: true #For fast IO :)
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4-turbo
  data:
    mongodb:
      uri: ${MONGO_ATLAS_URL_SERAVIA}
      auto-index-creation: true
      database: seravia_db

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000
