spring:
  application:
    name: Seravia
  threads:
    virtual:
      enabled: true #For fast IO :)
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4-turbo
  data:
    mongodb:
      uri: ${MONGO_ATLAS_URL_SERAVIA}
      auto-index-creation: true
      database: seravia_db
email:
  sendgrid:
    config:
      apiKey: ${SENDGRID_API_KEY}
      fromEmail: "ahnisaneja@gmail.com"

app:
  base-url: "http://localhost:8080"
  password-reset-url: "/api/v1/auth/reset-password"
security:
  allowedOrigins:
    - "http://localhost:63342"

management:
  endpoint:
    health:
      show-details: "always"  # Always show detailed health info (safe for internal use)
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/monitor"  # Moves all Actuator endpoints under "/monitor"
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000
admin:
  bootstrap:
    enabled: ${ADMIN_BOOTSTRAP_ENABLED:false}   # Default off for safety (dev only)
    resource: ${ADMIN_BOOTSTRAP_RESOURCE:classpath:/bootstrap/users.json}  # Default to classpath, can point to file:// or even http:// if needed (super flexible)
  user:
    enabled: ${ADMIN_ENABLED:true}  # Default false for safety
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@example.com}
    password: ${ADMIN_PASSWORD:admin123}  # Set via env var in production
    preferences:
      reportFrequency: BIWEEKLY  # Enum value
      language: ENGLISH          # Enum value
      themePreference: DARK      # Enum value
      supportStyle: MINDFUL   # Enum value
      age: 22                    # Integer value
      gender: MALE               # Enum value
server:
  port: 8081
