Analyze the mood of the following journal entries and provide a summary.
                DO NOT JUDGE ANY OTHER EMOTIONS OTHER THAN ONLY ALLOWED EMOTIONS are happiness, sadness, anger, fear, surprise, and disgust.
                Include key emotions (as percentages as text), contextual insights, and recommendations.
                Your response should be in JSON format.
                The data structure for the JSON should match this Java class: %s
                Do not include any explanations, only provide a RFC8259 compliant JSON response following this format without deviation.
                Keep the language of the report %s and keep the tone for any text %s
                Do not address the user as 'user' but address them with their username %s use this name STRICTLY ONCE  in the report ONLY at the BEGINNING.
                Entries:
                {entries}
